version: "3"

networks:
  app-net:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    networks:
      - neighbor-net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    # May give error on windows
    networks:
      - neighbor-net
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - neighbor-net
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
